---
# COPY and this file to secrets.yml and modify as needed
development:
  DATABASE_URL: sqlite://app/db/store/development.db
  DB_KEY: 3TluP6f7e1+wNrIqJdp3wfc4X/3ZrzKGLCZ+tz2yT6Y=
  SECURE_SCHEME: HTTP
  MSG_KEY: 18gFYqNxgpMzRAVAwhufwb3zD9vySDhMDHQZ8ZeOrpg=
  SENDGRID_API_URL: https://api.sendgrid.com/v3/mail/send
  SENDGRID_API_KEY: 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
  SENDGRID_FROM_EMAIL: fong54388+giftlist@gmail.com
  GITHUB_ACCOUNT_URL: https://api.github.com/user

test:
  DATABASE_URL: sqlite://app/db/store/test.db
  DB_KEY: y94pPLwLUYOunw26YT2j4ToPi2xXb9HfkoN4+Ja1m0o=
  SECURE_SCHEME: HTTP
  MSG_KEY: 18gFYqNxgpMzRAVAwhufwb3zD9vySDhMDHQZ8ZeOrpg=
  SENDGRID_API_URL: https://api.sendgrid.com/v3/mail/send
  SENDGRID_API_KEY: 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
  SENDGRID_FROM_EMAIL: fong54388+giftlist@gmail.com
  GITHUB_ACCOUNT_URL: https://api.github.com/user

production:
  DATABASE_URL: <set to production DB>
  DB_KEY: bc5ivX29oYRBEZTeiw+ehABeKv3bjq3yQMfbks55Rns=
  SECURE_SCHEME: HTTPS
  MSG_KEY: 18gFYqNxgpMzRAVAwhufwb3zD9vySDhMDHQZ8ZeOrpg=
  SENDGRID_API_URL: https://api.sendgrid.com/v3/mail/send
  SENDGRID_API_KEY: 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
  SENDGRID_FROM_EMAIL: fong54388+giftlist@gmail.com
  GITHUB_ACCOUNT_URL: https://api.github.com/user

